name: CI workflow

#Events
on: push

#List of jobs
jobs: 
  test:
    #runner
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    # Job steps
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            fetch-depth: 0 # fetch full history

        - name: Set up Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install dependencies
          run: npm install

        - name: Run the tests
          run: npm test -- --coverage --collectCoverageFrom="./src/**"

        - name: Upload code coverage to Codecov
          uses: codecov/codecov-action@v2
        
        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v3
          env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

        - name: Publish to Chromatic
          uses: chromaui/action@v1
          with:
            projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}